version: '3'
services:
  flask-app:
    build: .
    container_name: flask-con
    ports:
      - "4000:4000"
    networks:
      - my-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis
    container_name: redis-con
    networks:
      - my-network
    ports:
      - "6379:6379"

networks:
  my-network: